#module load intel
#module load intelmpi

./configLB3D.sh CONFIG JOULE -DSINGLEFLUID -DINTERPOLATEDBB -DMD  #-DVELCONTROL #-DDEBUG #-DMRT_SINGLEPARTICLE #-DFORCECOMPONENT # -DDEBUG # -DDEBUG_MPI
./configLB3D.sh MAKE-NODOC
#-DCOMMON_VEL_FIX #-DFORCE_BALANCE
