#!/bin/bash
f=$2
if [ "x$f" = "x" ]
  then f="/dev/stdout"
fi
h5dump $1  |  grep : | \
awk '{gsub(/[\(,: \)]+/," ");print}' \
| awk '{ if(match("version",$3)){exit} \
  print $3+1 " " $2+1 " " $1+1 " " $5 " "  $6 " " $7 " " sqrt($5**2+$6**2+$7**2)}' > $f
