#!/bin/ksh
# We use LSF now !


# File/Dir variables

CODEDIR=`pwd`
INPUTDIR=$CODEDIR/input
OUTDIR=$CODEDIR/../output
PROJECT="shear_ow"
GROUT=shear

# Run script paramters
NP=64
TL="320"
RUNHOST=green
POSTQUEUE=normal

# Fixed simulation parameters

NX=64
N_IT=10000

FB_START=2
FB_END=3
FB_STEP=1

FR=0

FG_START=2
FG_END=3
FG_STEP=1

SHEAR_START=2
SHEAR_END=3
SHEAR_STEP=1
################################################################
#
# Loops
#
################################################################

mkdir -p $INPUTDIR
mkdir -p $OUTDIR

FB_TMP=$FB_START
while [ $FB_TMP -le $FB_END ] ; do

 FG_TMP=$FG_START
 while [ $FG_TMP -le $FG_END ] ; do

 FR_TMP=0

FR=0.0
FB=0.$FB_TMP
FG=0.$FG_TMP

INPUTPREFIX=$PROJECT'_nx'$NX'_it'$N_IT'_fr'$FR'fb'$FB'fg'$FG
INPUTFILE=$INPUTPREFIX.in
OUTPUTFILE=$INPUTPREFIX.out
STDERRFILE=$INPUTPREFIX.err
RUNFILE=$INPUTPREFIX.run
POSTFILE=$INPUTPREFIX.post
PROJECTDIR=$PROJECT'_fb'$FB'_fg'$FG
OUTPREFIX='fb'$FB'_fg'$FG

echo $INPUTPREFIX

################################################################
#  Create input file
################################################################

echo "Input file is "$INPUTFILE
cat > $INPUTDIR/$INPUTFILE << EOF
&fixed_input
nx = $NX
ny = $NX
nz = $NX
seed = 1
obs_file = 'empty.dat'
boundary_cond = 0
/

&variable_input
n_iteration = $N_IT
sci_start = 0
n_sci = 200
sci_int = .true.
sci_sur = .true.
n_sci_sur = 200
sci_owd = .true.
n_sci_owd = 200 
sci_dir = .true.
n_sci_dir = 200
sci_vel = .false.
n_sci_vel = 200
sci_flo = .false.
n_sci_flo = 200
sci_arrows = .false.
n_sci_arrows = 200
sci_pressure = .false.
n_sci_pressure = 200
sci_pressure_init = 0
post=.true.
steer=.false.
folder = '$PROJECTDIR'
gr_out_file = '$OUTPREFIX'
init_cond = 0
fr = $FR
fg = $FG
fb = $FB
fr1 = 15
fr2 = 15
pr = 0.0
pb = 0.0
pg = 0.0
inv_fluid = 0
rock_colour = 0
beta = 10.0
/

&steer_input
use_ReG_steer = .true.
ReG_sample_format = 'xdr'
ReG_sample_field = 'colour'
ReG_sample_name_fixed = .true.
ReG_monitor_nt = .true.
ReG_monitor_n_sci = .true.
ReG_monitor_n_sci_sur = .true.
ReG_monitor_n_sci_owd = .true.
ReG_monitor_n_sci_dir = .true.
ReG_monitor_n_sci_vel = .true.
ReG_monitor_n_sci_flo = .true.
ReG_monitor_n_sci_arrows = .true.
ReG_monitor_n_sci_pressure = .true.
use_auto_steer = .false.
auto_steer_cmd_file = 'steer-cmd'
checkpoint_before_steer = .true.
steer_dump_fac = .true.
steer_fr = .true.
steer_fb = .false.
steer_fg = .false.
steer_beta = .false.
steer_tau_b = .false.
steer_tau_r = .false.
steer_tau_s = .false.
steer_tau_d = .false.
steer_amass_b = .false.
steer_amass_r = .false.
steer_amass_s = .false.
steer_g_br = .true.
steer_g_bs = .true.
steer_g_ss = .true.
steer_shear_u = .false.
steer_shear_omega = .false.
steer_checkpoint = .true.
/

&lbe_input
amass_b = 1.0
amass_r = 1.0
amass_s = 1.0
tau_b = 1.0
tau_r = 1.0
tau_s = 1.0
tau_d = 1.0
g_br = 0.08
g_bs = -0.006
g_ss = -0.001
d_0 = 1.0
bdist = 0
perturbation = 0
shear_u = 0
g_accn = 0
checkpoint = 10000
restore = 0
psifunc = 2
dump_format = 'xdr'
write_AVS_fld = .true.
dump_double = .true.
write_statistics = .true.
/
EOF

################################################################
#  Create run scripts
################################################################

JOBLABEL='Rb'$FB_TMP'g'$FG_TMP
echo "Run script is "$RUNFILE
cat > $INPUTDIR/$RUNFILE << EOF
#!/bin/sh
#BSUB -W $TL
#BSUB -B
#BSUB -n $NP
#BSUB -m $RUNHOST
#BSUB -J $JOBLABEL 
#BSUB -o $OUTPUTFILE
#BSUB -e $STDERRFILE
mkdir -p $OUTDIR/$PROJECTDIR
cp $INPUTDIR/$INPUTFILE $OUTDIR/$PROJECTDIR/
cp $INPUTDIR/$INPUTFILE $CODEDIR/
cd $CODEDIR
echo INTERACTIVE >.input-file
date
echo "$INPUTFILE"| mpirun -np $NP ./lbe
rm -f $INPUTFILE
mkdir -p $INPUTDIR/done
mv $INPUTDIR/$RUNFILE $INPUTDIR/done/ 
mv $INPUTDIR/$INPUTFILE $INPUTDIR/done/ 
date
EOF
#qsub $INPUTDIR/$POSTFILE

chmod a+x $INPUTDIR/$RUNFILE

###################################


   let FG_TMP=$FG_TMP+$FG_STEP
  done
 let FB_TMP=$FB_TMP+$FB_STEP
done
