#include <stdio.h>
#include <stdlib.h>
#include <rpc/rpc.h>

int main (int argc, char *argv[])
{

	FILE *infile,*outfile,*outfile2;
	char *infname,*outfname,*outfname2;
	XDR xdrs;
        float p3,p4;
	int nx,ny,nz;
	int i,x,y,z;
#ifdef SGL
	float sum;
	float *phi,*p,*phi2,*p2;
#else
	double sum;
	double *phi,*p,*phi2,*p2;
#endif

	if (argc!=7) {
		fprintf(stderr,"Usage: %s <nx> <ny> <nz> <infile> <outfile> <outfile2>\n",
			argv[0]);
		return -1;
	}

	nx=atoi(argv[1]);
	ny=atoi(argv[2]);
	nz=atoi(argv[3]);
	infname=argv[4];
	outfname=argv[5];
	outfname2=argv[6];
	if ( (nx<=0) || (ny<=0) ) {
		fprintf(stderr,"Bad dimensions: %d x %d\n",nx,ny);
		return -1;
	}

#ifdef SGL
	if (NULL==(phi=malloc(sizeof(float)*nx*ny*nz))) {
		perror("malloc()");
		return -1;
	}
	if (NULL==(phi2=malloc(sizeof(float)*nx*ny*nz))) {
		perror("malloc()");
		return -1;
	}
#else
	if (NULL==(phi=malloc(sizeof(double)*nx*ny*nz))) {
		perror("malloc()");
		return -1;
	}
	if (NULL==(phi2=malloc(sizeof(double)*nx*ny*nz))) {
		perror("malloc()");
		return -1;
	}
#endif

	if (NULL==(infile=fopen(infname,"r"))) {
		perror("fopen()");
		return -1;
	}
	if (NULL==(outfile=fopen(outfname,"w"))) {
		perror("fopen()");
		return -1;
	}
	if (NULL==(outfile2=fopen(outfname2,"w"))) {
		perror("fopen()");
		return -1;
	}

	/* Snarf the data into one large buffer, taking a sum as we go along.
	 */

	xdrstdio_create(&xdrs,infile,XDR_DECODE);

	p=phi;
	p2=phi2;
	sum=0.0;
	for (i=0;i<nx*ny*nz;i++) {
#ifdef SGL
		if (1!=xdr_float(&xdrs,p++)) {
			fprintf(stderr,"xdr_float() failed on datum %d.\n",i);
			return -1;
		}
		if (1!=xdr_float(&xdrs,p2++)) {
			fprintf(stderr,"xdr_float() failed on datum %d.\n",i);
			return -1;
		}
#else
		if (1!=xdr_double(&xdrs,p++)) {
			fprintf(stderr,"xdr_double() failed on datum %d.\n",i);
			return -1;
		}
		if (1!=xdr_double(&xdrs,p2++)) {
			fprintf(stderr,"xdr_double() failed on datum %d.\n",i);
			return -1;
		}
#endif
		sum+= *(p-1);
	}
	xdr_destroy(&xdrs);
	fclose(infile);

	/* Set "sum" to contain the mean */

	sum/=(float)(nx*ny);

	/* Start writing vtk file */

	fprintf(outfile,"# vtk DataFile Version 2.0\nGenerated by xdr2vtk\nBINARY\n");
	fprintf(outfile,"DATASET STRUCTURED_POINTS\n");
	fprintf(outfile,"DIMENSIONS %d %d %d\n",nx,ny,nz);
	fprintf(outfile,"SPACING 1 1 1\n");
	fprintf(outfile,"ORIGIN 0 0 0\n");
	fprintf(outfile,"POINT_DATA %d\n",nx*ny*nz);
	fprintf(outfile,"SCALARS scalars float\n");
	fprintf(outfile,"LOOKUP_TABLE default\n");

	fprintf(outfile2,"# vtk DataFile Version 2.0\nGenerated by xdr2vtk\nBINARY\n");
	fprintf(outfile2,"DATASET STRUCTURED_POINTS\n");
	fprintf(outfile2,"DIMENSIONS %d %d %d\n",nx,ny,nz);
	fprintf(outfile2,"SPACING 1 1 1\n");
	fprintf(outfile2,"ORIGIN 0 0 0\n");
	fprintf(outfile2,"POINT_DATA %d\n",nx*ny*nz);
	fprintf(outfile2,"SCALARS scalars float\n");
	fprintf(outfile2,"LOOKUP_TABLE default\n");
	p=phi;
	p2=phi2;
	for (z=0;z<nz;z++) {
	for (y=0;y<ny;y++) {
	for (x=0;x<nx;x++) {
                p3 = *p++;
		fwrite(&p3,sizeof(float),1,outfile);
                p4 = *p2++;
		fwrite(&p4,sizeof(float),1,outfile2);
	}
	}
	}

	fclose(outfile);
	fclose(outfile2);
	free(phi);
	free(phi2);
	return 0;
}
