/* Translate X-ray microtomography data to VTK format */
#include <stdio.h>
#include <stdlib.h>

#define XMT_HEADER_SIZE 512
#define BUFFERSIZE 2097152 /* 2 meg buffer */

int main (int argc, char *argv[])
{

	FILE *infile,*outfile;
	char *infname,*outfname;
	unsigned int nx,ny,nz;
	int i;
	unsigned char *buffer[BUFFERSIZE];
	unsigned int nblocks;
	size_t rump;


	if (argc!=6) {
		fprintf(stderr,"Usage: %s <nx> <ny> <nz> <infile> <outfile>\n",
			argv[0]);
		return -1;
	}

	nx=atoi(argv[1]);
	ny=atoi(argv[2]);
	nz=atoi(argv[3]);
	infname=argv[4];
	outfname=argv[5];
	if ( (nx<=0) || (ny<=0) ) {
		fprintf(stderr,"Bad dimensions: %d x %d\n",nx,ny);
		return -1;
	}

	if (NULL==(infile=fopen(infname,"r"))) {
		perror("fopen()");
		return -1;
	}
	if (NULL==(outfile=fopen(outfname,"w"))) {
		perror("fopen()");
		return -1;
	}

	/* Skip 512-byte header */

	if (-1==fseek(infile,XMT_HEADER_SIZE,SEEK_SET)) {
		perror("fseek()");
		return -1;
	}

	/* Start writing vtk file */

	fprintf(outfile,"# vtk DataFile Version 2.0\nGenerated by xmt2vtk\nBINARY\n");
	fprintf(outfile,"DATASET STRUCTURED_POINTS\n");
	fprintf(outfile,"DIMENSIONS %d %d %d\n",nx,ny,nz);
	fprintf(outfile,"SPACING 1 1 1\n");
	fprintf(outfile,"ORIGIN 0 0 0\n");
	fprintf(outfile,"POINT_DATA %d\n",nx*ny*nz);
	fprintf(outfile,"SCALARS scalars unsigned_char\n");
	fprintf(outfile,"LOOKUP_TABLE default\n");

	nblocks=nx*ny*nz/BUFFERSIZE;
	for (i=0;i<nblocks;i++) {
		if (1!=fread(buffer,BUFFERSIZE,1,infile)) {
			perror("fread()");
			fprintf(stderr,"Died at line %d\n",__LINE__);
			return -1;
		}
		if (1!=fwrite(buffer,BUFFERSIZE,1,outfile)) {
			perror("fwrite()");
			fprintf(stderr,"Died at line %d\n",__LINE__);
			return -1;
		}

	}
	/* Do the last chunk */
	rump = (nx*ny*nx)%BUFFERSIZE;
	if (1!=fread(buffer,rump,1,infile)) {
		if (ferror(infile)) {
			perror("fread()");
			fprintf(stderr,"Died at line %d\n",__LINE__);
			return -1;
		}
	}
	if (1!=fwrite(buffer,rump,1,outfile)) {
		perror("fwrite()");
		fprintf(stderr,"Died at line %d\n",__LINE__);
		return -1;
	}


	fclose(infile);
	fclose(outfile);
	return 0;
}
