# Welche Configuration soll verwendet werden
T_WITH_CONFIG=g++

# C++ Compiler
CXX = g++

ifeq (no, yes)
 T_ENABLE_DEBUG=yes
endif

# wo ist QT zu finden
QTDIR=/usr/lib/qt3
GLINCLUDEDIR=/usr/include
GLLIBDIR=/usr/lib64
GLUINCLUDEDIR=/usr/include
GLULIBDIR=/usr/lib64
X11DIR=/usr/X11R6

include $(BASEPATH)/CONFIG/$(T_WITH_CONFIG)

QTINCLUDEDIR=$(QTDIR)/include
QTLIBDIR=$(QTDIR)/lib64
QTBINDIR=$(QTDIR)/bin
MOC=$(QTBINDIR)/moc

X11INCLUDEDIR=$(X11DIR)/include
X11LIBDIR=$(X11DIR)/lib

prefix = /usr/local
exec_prefix = ${prefix}


CPPFLAGS = $(LOCAL_CPPFLAGS) -I. -I.. -I$(BASEPATH) -I$(BASEPATH)/T -I$(BASEPATH)/D -I$(BASEPATH)/G -I$(QTINCLUDEDIR) -I$(GLINCLUDEDIR) -I$(GLUINCLUDEDIR) -I$(X11INCLUDEDIR)
CXXFLAGS = $(OPTFLAGS)
LDFLAGS= $(RPATH)

AS = @GAS@

INSTALL = /usr/bin/install -c

LN_S = ln -s


.SUFFIXES: .cc

.cc.o:
	$(CXX) -DWITH_QT $(CXXFLAGS) $(CPPFLAGS) -c -o $@ $<

%_moc.cc: %.h
	$(MOC) -o $@ $<

.depend:
	$(CXX) -DWITH_QT $(CPPFLAGS) -M $(SRCS) > $@
