#!/usr/sbin/perl

my $outfile = shift;
my $nx=shift;
my $ny=shift;
my $nz=shift;
my $ox = shift;
my $oy = shift;
my $oz = shift;

open (OUTFILE,">$outfile") or die ("Unable to open $outfile");

for my $z ( $oz..($oz+$nz-1) ) {
	for my $y ( $oy..($oy+$ny-1) ) {
		for my $x ( $ox..($ox+$nx-1) ) {
			print OUTFILE "$x $y $z 1\n";
		}
	}
}

close OUTFILE;
