all:
	/usr/local/intel/11.1/046/bin/intel64/icpc -g -o h5converter h5converter.cpp -lhdf5 -Wall -I/usr/local/HDF5/hdf5-1.8.8-linux-x86_64-shared/include -L/usr/local/HDF5/hdf5-1.8.8-linux-x86_64-shared/lib/
	/usr/local/intel/11.1/046/bin/intel64/icpc -g -o h5clustersplit h5clustersplit.cpp -lhdf5 -Wall -I/usr/local/HDF5/hdf5-1.8.5-patch1-linux-x86_64-shared/include -L/usr/local/HDF5/hdf5-1.8.5-patch1-linux-x86_64-shared/lib

clean:
	rm -f h5converter
